# Generated by Django 2.2.10 on 2020-03-20 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=255, verbose_name='business_name')),
                ('business_website', models.CharField(blank=True, max_length=255, verbose_name='business_website')),
                ('description', models.TextField(max_length=500, verbose_name='description')),
                ('extra_field_1', models.CharField(blank=True, max_length=255, verbose_name='extra_field_1')),
                ('extra_field_2', models.CharField(blank=True, max_length=255, verbose_name='extra_field_2')),
                ('extra_field_3', models.CharField(blank=True, max_length=255, verbose_name='extra_field_3')),
                ('extra_field_4', models.CharField(blank=True, max_length=255, verbose_name='extra_field_4')),
                ('extra_field_5', models.CharField(blank=True, max_length=255, verbose_name='extra_field_5')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published_at')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='subtitle')),
                ('thumbnail_url', models.TextField(blank=True, verbose_name='thumbnail_url')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('video_url', models.TextField(verbose_name='video_url')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'published_at',
                'ordering': ['-published_at'],
                'verbose_name_plural': 'videos',
                'verbose_name': 'video',
            },
        ),
    ]
