# Generated by Django 2.2.10 on 2020-05-15 23:35

from django.db import migrations, models
import django.db.models.deletion
import info.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0002_auto_20200320_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('photo_url', models.TextField(verbose_name='photo_url')),
                ('showreel_url', models.TextField(verbose_name='showreel_url')),
            ],
            options={
                'verbose_name': 'About Page Info',
            },
        ),
        migrations.CreateModel(
            name='HomeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.CharField(blank=True, max_length=255, verbose_name='facebook_url')),
                ('instagram_url', models.CharField(blank=True, max_length=255, verbose_name='instagram_url')),
                ('twitter_url', models.CharField(blank=True, max_length=255, verbose_name='twitter_url')),
                ('video_banner_url', models.TextField(verbose_name='video_banner_url')),
                ('logo_url', models.TextField(verbose_name='logo_url')),
                ('info_1', models.CharField(blank=True, max_length=255, verbose_name='info_1')),
                ('info_2', models.CharField(blank=True, max_length=255, verbose_name='info_2')),
                ('featured_video', models.OneToOneField(default=info.models.get_latest_video_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='videos.Video')),
            ],
            options={
                'verbose_name': 'Home Page Info',
            },
        ),
    ]
